export type GooglePayPayload = {
  shippingFirstName: string;
  shippingLastName: string;
  shippingAddress1: string;
  shippingAddress2: string;
  shippingCity: string;
  shippingCountry: string;
  shippingPostalCode: string;
  shippingPhoneNumber: string;
  shippingState: string;
  firstName: string;
  lastName: string;
  address1: string;
  address2: string;
  city: string;
  country: string;
  postalCode: string;
  state: string;
  cardNetwork: string;
  cardDetails: string;
  cardDisplayName: string;
  phoneNumber: string;
  useRegistryAddress: boolean | null;
  orderShipType: string;
  token: string;
  tokenType: string;
  description: string;
  email: string;
};