# Gitleaks configuration file

title = "Gitleaks Config"

[allowlist]
paths = [
    '''node_modules''',
    '''dist''',
    '''playwright-report''',
    '''test-results''',
]

# Example config for commonly exposed secrets
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(['"]?(?:api[_-]?key|apikey|token)['"]\s*[:=]\s*['"]?[A-Za-z0-9+/=]{16,}['"]?)'''
secret-group = 1
entropy = 3.5

[[rules]]
id = "playwright-password"
description = "Potential Playwright Test Password"
regex = '''(?i)(['"]?(?:password|pwd|passwd)['"]\s*[:=]\s*['"][^'"]{8,}['"])'''
secret-group = 1
entropy = 3.0

[[rules]]
id = "playwright-username"
description = "Potential Playwright Test Username"
regex = '''(?i)(['"]?(?:username|user|login)['"]\s*[:=]\s*['"][^'"]{3,}['"])'''
secret-group = 1

[[rules]]
id = "environment-variable"
description = "Environment Variable"
regex = '''(?i)(['"]?(?:PLAYWRIGHT_|TEST_)[A-Z_]+['"]?\s*[:=]\s*['"][^'"]+['"])'''
secret-group = 1